---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store reference architecture and workshop notebooks.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: "Retail Demo Store Deployment Configuration"
        Parameters:
          - ResourceBucket
          - ResourceBucketRelativePath
          - CreateElasticsearchServiceLinkedRole
      - Label: 
          default: "Source Deployment Approach"
        Parameters: 
          - SourceDeploymentType
      - Label: 
          default: "GitHub Linked Deployment (only required for GitHub deployment approach)"
        Parameters: 
          - GitHubRepo
          - GitHubBranch
          - GitHubToken
          - GitHubUser
      - Label:
          default: "Auto-Build Resources"
        Parameters:
          - PreIndexElasticsearch
          - PreCreatePersonalizeCampaign
      - Label:
          default: "Miscellaneous"
        Parameters:
          - AmplitudeApiKey
          - OptimizelySdkKey
    ParameterLabels:
      ResourceBucket:
        default: "Deployment Resources Staging Bucket Name"
      ResourceBucketRelativePath:
        default: "Deployment Resources Staging Bucket Relative Path (optional)"
      CreateElasticsearchServiceLinkedRole:
        default: "Create Elasticsearch Service Role?"
      SourceDeploymentType:
        default: "Deployment Type"
      GitHubRepo:
        default: "GitHub Repository Name"
      GitHubBranch:
        default: "GitHub Branch"
      GitHubToken:
        default: "GitHub Personal Access Token"
      GitHubUser:
        default: "GitHub Username"
      PreIndexElasticsearch:
        default: "Auto-Load Elasticsearch Index"
      PreCreatePersonalizeCampaign:
        default: "Auto-Build Personalize Campaigns"
      AmplitudeApiKey:
        default: "Amplitude API Key"
      OptimizelySdkKey:
        default: "Optimizely SDK Key"

Parameters:
  ResourceBucket:
    Type: String
    Description: >
      S3 bucket name where the Retail Demo Store deployment resources are staged (product images, nested CloudFormation templates, source code snapshot, 
      notebooks, deployment Lambda code, etc).

  ResourceBucketRelativePath:
    Type: String
    Description: >
      Optional path in the Deployment Resources Staging bucket where the deployment resources are stored (e.g. path/path2/). 
      Leave blank if resources are at the root of the Staging Resource Bucket. If specified, MUST end with '/'.

  CreateElasticsearchServiceLinkedRole:
    Type: String
    Description: >
      If your account already has an IAM Role named 'AWSServiceRoleForAmazonElasticsearchService', select 'No'. Otherwise, select 'Yes' and one will be created automatically.
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'

  SourceDeploymentType:
    Type: String
    Description: >
      The Retail Demo Store deployment includes a CodePipeline configuration that will build and deploy Retail Demo Store 
      microservices to ECS when a change is detected in the source repository. The source repository for CodePipeline 
      can be configured to use your personal GitHub repository or CodeCommit. Use GitHub if you're actively developing 
      against Retail Demo Store in your own fork. CodeCommit is useful when you just want to get up and going quickly for 
      a demo or evaluation or for workshop scenarios, such as Event Engine, where you want attendees to have their own 
      source repositories provisioned.
    AllowedValues:
      - 'GitHub'
      - 'CodeCommit'
    Default: 'CodeCommit'

  GitHubRepo:
    Type: String
    Description: Name of Retail Demo Store GitHub repository in your GitHub account.
    Default: retail-demo-store

  GitHubBranch:
    Type: String
    Description: Name of GitHub branch to link to this Retail Demo Store deployment.
    Default: master

  GitHubToken:
    Type: String
    Description: GitHub Personal Access Token for your GitHub account. Be sure that your token has the "repo", "repo:status", and "admin:repo_hook" permission scopes.
    NoEcho: true

  GitHubUser:
    Type: String
    Description: Your GitHub username.

  PreIndexElasticsearch:
    Type: String
    Description: >
      Deploy Lambda function that automatically indexes the Retail Demo Store products in Elasticsearch. Otherwise, select 'No' if you would 
      prefer to complete this process yourself by stepping through the Search workshop included in your deployment as a Jupyter notebook in SageMaker.
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'

  PreCreatePersonalizeCampaign:
    Type: String
    Description: >
      Deploy Lambda function that automatically builds solutions and launches Personalize campaigns. Otherwise, select 'No' if you would 
      prefer to complete this process yourself by stepping through the Personalization workshop included in your deployment as a Jupyter notebook 
      in SageMaker.
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'

  AmplitudeApiKey:
    Type: String
    Description: Amplitude API key for integrated product analytics and A/B testing results (optional).
    NoEcho: true

  OptimizelySdkKey:
    Type: String
    Description: Optimizely SDK key for experimentation (optional).
    NoEcho: true

Resources:
  # String macro Resource
  String:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}cloudformation-templates/string.yaml

  #Base template
  App:
    DependsOn: String
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}cloudformation-templates/_template.yaml
      Parameters:
        ResourceBucket: !Ref ResourceBucket
        ResourceBucketRelativePath: !Ref ResourceBucketRelativePath
        CreateElasticsearchServiceLinkedRole: !Ref CreateElasticsearchServiceLinkedRole
        SourceDeploymentType: !Ref SourceDeploymentType
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken
        GitHubUser: !Ref GitHubUser
        PreIndexElasticsearch: !Ref PreIndexElasticsearch
        PreCreatePersonalizeCampaign: !Ref PreCreatePersonalizeCampaign
        AmplitudeApiKey: !Ref AmplitudeApiKey
        OptimizelySdkKey: !Ref OptimizelySdkKey
        ParentStackName: !Ref AWS::StackName
    
Outputs:
  UserPoolId:
    Description: Authentication Cognito User Pool Id.
    Value: !GetAtt App.Outputs.UserPoolId
  
  UserPoolClientId:
    Description: Authentication Cognito User Pool Client Id.
    Value: !GetAtt App.Outputs.UserPoolClientId
  
  IdentityPoolId:
    Description: Authentication Cognito Identity Pool Id.
    Value: !GetAtt App.Outputs.IdentityPoolId

  StackBucketName:
    Description: Stack Bucket Name
    Value: !GetAtt App.Outputs.StackBucketName

  NotebookInstanceId:
    Description: Notebook Instance Id.
    Value: !GetAtt App.Outputs.NotebookInstanceId

  VpcId:
    Description: VPC Id.
    Value: !GetAtt App.Outputs.VpcId

  Subnets:
    Description: Service Subnets.
    Value: !GetAtt App.Outputs.Subnets

  ClusterName:
    Description: ECS Cluster Name.
    Value: !GetAtt App.Outputs.ClusterName

  WebUICDNURL:
    Description: Retail Demo Store Web UI URL
    Value: !GetAtt App.Outputs.WebUICDNURL

  ElasticsearchDomainEndpoint:
    Description: Elasticsearch Endpoint
    Value: !GetAtt App.Outputs.ElasticsearchDomainEndpoint

  PinpointAppId:
    Description: Pinpoint App Id.
    Value: !GetAtt App.Outputs.PinpointAppId
