---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store CloudFront distribution for the Web-UI and static assets.

Parameters:
  CleanupBucketLambdaArn:
    Type: String
    Description: Lambda Arn for cleanup function

Conditions:
  IADRegion: !Equals [!Ref "AWS::Region", "us-east-1"]

Resources:
  
  # Web UI infrastructure    
  WebUIBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html

  # Empties bucket when stack is deleted
  EmptyWebUIBucket:
    Type: Custom::EmptyStackBucket
    Properties:
      ServiceToken: !Ref CleanupBucketLambdaArn
      BucketName: !Ref WebUIBucket

  WebUIBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebUIBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${WebUIBucket}/*'
            Principal:
              AWS: !Sub >-
                arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${WebUIBucketOriginAccessIdentity}

  WebUIBucketOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OriginAccessIdentity for ${WebUIBucket}'

  WebUICDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Retail Demo Store CDN for ${WebUIBucket}'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        HttpVersion: http2
        Origins:
          - DomainName: !Join
              - ''
              - - !Sub '${WebUIBucket}.s3'
                - !If [IADRegion, '', !Sub '-${AWS::Region}']
                - '.amazonaws.com'
            Id: S3
            S3OriginConfig:
              OriginAccessIdentity: !Sub >-
                origin-access-identity/cloudfront/${WebUIBucketOriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: 'true'

  # Swagger UI infrastructure
  SwaggerUIBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html

  # Empties bucket when stack is deleted
  EmptySwaggerUIBucket:
    Type: Custom::EmptyStackBucket
    Properties:
      ServiceToken: !Ref CleanupBucketLambdaArn
      BucketName: !Ref SwaggerUIBucket

  SwaggerUIBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SwaggerUIBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${SwaggerUIBucket}/*'
            Principal:
              AWS: !Sub >-
                arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${SwaggerUIBucketOriginAccessIdentity}

  SwaggerUIBucketOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OriginAccessIdentity for ${SwaggerUIBucket}'

  SwaggerUICDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Swagger UI CDN for ${SwaggerUIBucket}'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        HttpVersion: http2
        Origins:
          - DomainName: !Join
              - ''
              - - !Sub '${SwaggerUIBucket}.s3'
                - !If [IADRegion, '', !Sub '-${AWS::Region}']
                - '.amazonaws.com'
            Id: S3
            S3OriginConfig:
              OriginAccessIdentity: !Sub >-
                origin-access-identity/cloudfront/${SwaggerUIBucketOriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: 'true'

Outputs:
  # Web UI outputs
  WebUIBucketName:
    Description: Web UI S3 bucket for CloudFront distribution.
    Value: !Ref WebUIBucket

  WebUICDN:
    Description: CloudFront distribution ID for the Web UI CDN
    Value: !Ref WebUICDN

  # Since the Retail Demo Store web service load balancers are not deployed with SSL, 
  # the Web UI URL must be http to avoid mixed content errors in the browser.
  WebUICDNURL:
    Description: The URL for the web application
    Value: !Sub 
      - 'http://${Domain}'
      - Domain: !GetAtt WebUICDN.DomainName    

  # Swagger UI outputs
  SwaggerUIBucketName:
    Description: Swagger UI S3 bucket for CloudFront distribution.
    Value: !Ref SwaggerUIBucket

  SwaggerUICDN:
    Description: CloudFront distribution ID for the Swagger UI CDN
    Value: !Ref SwaggerUICDN

  # Since the Retail Demo Store web service load balancers are not deployed with SSL, 
  # the Swagger UI URL must be http to avoid mixed content errors in the browser.
  SwaggerUICDNURL:
    Description: The URL for the Swagger UI application
    Value: !Sub 
      - 'http://${Domain}'
      - Domain: !GetAtt SwaggerUICDN.DomainName