---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store ElasticSearch Cluster.

Parameters:

  Subnets:
    Type: String

  Subnet1:
    Type: String

  Subnet2:
    Type: String

  VpcId:
    Type: String

Resources:

  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '6.7'
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t2.small.elasticsearch
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: standard
      SnapshotOptions:
        AutomatedSnapshotStartHour: 0
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions:
        SubnetIds: 
          - !Ref Subnet1
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
      Tags:
        - 
          Key: "Name"
          Value: "retaildemostore"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Elasticsearch Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - FromPort: 443
          IpProtocol: tcp
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
 
  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
 
  SecurityGroupId:
    Value: !Ref SecurityGroup
