---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store Evidently project and features.

Parameters:
  Uid:
    Type: String

Resources:
  EvidentlyProject:
    Type: AWS::Evidently::Project
    Properties:
      Name: !Ref Uid
      Description: Retail Demo Store features and experiments

  FeatureHomeProductRecs:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-UserPersonalization
      Description: Home page product recommendations
      EvaluationStrategy: ALL_RULES
      Name: home_product_recs
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: FeaturedProducts
          StringValue: '{"type":"product"}'
        - VariationName: Personalize-UserPersonalization
          StringValue: !Sub '{"type":"personalize-recommendations","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:recommender/retaildemostore-recommended-for-you"}'

  FeatureHomeFeaturedRerank:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-PersonalizedRanking
      Description: Home page featured products carousel
      EvaluationStrategy: ALL_RULES
      Name: home_featured_rerank
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: RankingNoOp
          StringValue: '{"type":"ranking-no-op"}'
        - VariationName: Personalize-PersonalizedRanking
          StringValue: !Sub '{"type":"personalize-ranking","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-personalized-ranking"}'

  FeatureProductDetailRelated:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-Similar-Items
      Description: Product detail related products carousel
      EvaluationStrategy: ALL_RULES
      Name: product_detail_related
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: ProductsInSameCategory
          StringValue: '{"type":"product"}'
        - VariationName: OpenSearchMoreLikeThis
          StringValue: '{"type":"similar"}'
        - VariationName: Personalize-Similar-Items
          StringValue: !Sub '{"type":"personalize-recommendations","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-related-items"}'

  FeatureSearchResults:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-PersonalizedRanking
      Description: Search control auto-complete
      EvaluationStrategy: ALL_RULES
      Name: search_results
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: RankingNoOp
          StringValue: '{"type":"ranking-no-op"}'
        - VariationName: Personalize-PersonalizedRanking
          StringValue: !Sub '{"type":"personalize-ranking","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-personalized-ranking"}'

  FeatureLiveStreamProductRecs:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-PersonalizedRanking
      Description: Live stream product recommendations
      EvaluationStrategy: ALL_RULES
      Name: live_stream_prod_recommendation
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: RankingNoOp
          StringValue: '{"type":"ranking-no-op"}'
        - VariationName: Personalize-PersonalizedRanking
          StringValue: !Sub '{"type":"personalize-ranking","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-personalized-ranking"}'

  FeatureLiveStreamProductDiscounts:
    Type: AWS::Evidently::Feature
    Properties:
      DefaultVariation: Personalize-PersonalizedRanking
      Description: Live stream product discounts
      EvaluationStrategy: ALL_RULES
      Name: live_stream_prod_discounts
      Project: !Ref EvidentlyProject
      Variations:
        - VariationName: RankingNoOp
          StringValue: '{"type":"ranking-no-op"}'
        - VariationName: Personalize-PersonalizedRanking
          StringValue: !Sub '{"type":"personalize-ranking","arn":"arn:${AWS::Partition}:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-personalized-ranking"}'

Outputs:
  EvidentlyProjectName:
    Description: Evidently project name
    Value: !Ref Uid
