---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store OpenSearch domain.

Parameters:

  PrivateSubnets:
    Type: String

  VpcId:
    Type: String

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenSearch Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - FromPort: 443
          IpProtocol: tcp
          ToPort: 443
          CidrIp: 0.0.0.0/0
    
  AOSSVpcEndpoint:
    Type: AWS::OpenSearchServerless::VpcEndpoint
    Properties:
      Name: aoss-retaildemostore-vpcendpoint
      VpcId: !Ref VpcId
      SubnetIds: !Split [",", !Ref PrivateSubnets ]
      SecurityGroupIds:
        - !Ref SecurityGroup

  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: retaildemostore-security-policy
      Type: encryption
      Description: Encryption policy for the retail demo store collections
      Policy:
        !Sub |
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": [
                  "collection/retaildemostore*"
                ]
              }
            ],
            "AWSOwnedKey": true
          }

  NetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: retaildemostore-network-policy
      Type: network
      Description: Network policy for the retail demo store collections
      Policy:
        !Sub |
          [{
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": [
                  "collection/retaildemostore*"
                ]
              }
            ],
            "AllowFromPublic": false,
            "SourceVPCEs": [
              "${AOSSVpcEndpoint}"
            ]
           }]       

  Collection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn: EncryptionPolicy
    Properties:
      Name: retaildemostore-products
      Type: SEARCH
      StandbyReplicas: DISABLED
      Description: Collection to hold product data
      Tags:
        - Key: "Name"
          Value: "retaildemostore"

Outputs:
  CollectionArn:
    Value: !GetAtt Collection.Arn

  CollectionEndpoint:
    Value: !GetAtt Collection.CollectionEndpoint

  SecurityGroupId:
    Value: !Ref SecurityGroup