---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store OpenSearch domain.

Parameters:

  Subnet1:
    Type: String

  VpcId:
    Type: String

Resources:

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      EngineVersion: OpenSearch_2.3
      ClusterConfig:
        InstanceCount: 1
        InstanceType: t3.small.search
        ZoneAwarenessEnabled: false
      DomainEndpointOptions:
        EnforceHTTPS: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      EncryptionAtRestOptions:
        Enabled: true
      VPCOptions:
        SubnetIds:
          - !Ref Subnet1
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
      Tags:
        -
          Key: "Name"
          Value: "retaildemostore"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenSearch Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - FromPort: 443
          IpProtocol: tcp
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  DomainArn:
    Value: !GetAtt OpenSearchDomain.DomainArn

  DomainEndpoint:
    Value: !GetAtt OpenSearchDomain.DomainEndpoint

  SecurityGroupId:
    Value: !Ref SecurityGroup
