---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store SSM Parameters.

Parameters:
  StackBucketName:
    Type: String

  ExperimentStrategyTableName:
    Type: String

  AmplitudeApiKey:
    Type: String
    Description: Amplitude API key for product analytics and A/B testing results (optional).
    NoEcho: true

  OptimizelySdkKey:
    Type: String
    Description: Optimizely SDK key for experimentation (optional).
    NoEcho: true

  Uid:
    Type: String

Conditions:
  HasAmplitudeApiKey:
    !Not [!Equals [!Ref AmplitudeApiKey, ""]]
  HasOptimizelySdkKey:
    !Not [!Equals [!Ref OptimizelySdkKey, ""]]

Resources:

  ParameterStackBucketName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-stack-bucket'
      Type: "String"
      Value: !Ref StackBucketName
      Description: "Retail Demo Store Stack Bucket Parameter"

  ParameterRelatedProductsCampaignArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-related-products-campaign'
      Type: "String"
      Value: "NONE"
      Description: "Retail Demo Store Related Products Campaign Arn Parameter"

  ParameterProductRecommendationCampaignArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-product-recommendation-campaign'
      Type: "String"
      Value: "NONE"
      Description: "Retail Demo Store Product Recommendation Campaign Arn Parameter"

  ParameterPersonalizedRankingCampaignArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-personalized-ranking-campaign'
      Type: "String"
      Value: "NONE"
      Description: "Retail Demo Store Personalized Ranking Campaign Arn Parameter"

  ParameterPersonalizeFilterPurchasedArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-personalize-filter-purchased'
      Type: "String"
      Value: "NONE"
      Description: "Retail Demo Store Personalize Filter Purchased Products Arn Parameter"

  ParameterExperimentStrategyTableName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-experiment-strategy-table-name'
      Type: "String"
      Value: !Ref ExperimentStrategyTableName
      Description: "Retail Demo Store Experiment Strategy DDB Table Name"

  ParameterPersonalizeEventTrackerId:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-personalize-event-tracker-id'
      Type: "String"
      Value: "NONE"
      Description: "Retail Demo Store Personalize Event Tracker ID Parameter"
      
  ParameterAmplitudeApiKey:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-amplitude-api-key'
      Type: "String"
      Value: !If [HasAmplitudeApiKey, !Ref AmplitudeApiKey, 'NONE']
      Description: "Retail Demo Store Amplitude API key"

  ParameterOptimizelySdkKey:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${Uid}-optimizely-sdk-key'
      Type: "String"
      Value: !If [HasOptimizelySdkKey, !Ref OptimizelySdkKey, 'NONE']
      Description: "Retail Demo Store Optimizely SDK key"

Outputs:

  ParameterStackBucketName:
    Description: Stack Bucket Name Parameter
    Value: !Ref ParameterStackBucketName

  ParameterRelatedProductsCampaignArn:
    Description: Related Products Campaign Arn Parameter
    Value: !Ref ParameterRelatedProductsCampaignArn
    
  ParameterProductRecommendationCampaignArn:
    Description: Product Recommendation Campaign Arn Parameter
    Value: !Ref ParameterProductRecommendationCampaignArn

  ParameterPersonalizedRankingCampaignArn:
    Description: Personalized Ranking Campaign Arn
    Value: !Ref ParameterPersonalizedRankingCampaignArn

  ParameterPersonalizeFilterPurchasedArn:
    Description: Personalize Filter Purchased Products Arn
    Value: !Ref ParameterPersonalizeFilterPurchasedArn
  
  ParameterExperimentStrategyTableName:
    Description: Experiment Strategy Table Name
    Value: !Ref ParameterExperimentStrategyTableName

  ParameterPersonalizeEventTrackerId:
    Description: Personalize Event Tracker ID Parameter
    Value: !Ref ParameterPersonalizeEventTrackerId

  ParameterAmplitudeApiKey:
    Description: Amplitude API key
    Value: !Ref ParameterAmplitudeApiKey

  ParameterOptimizelySdkKey:
    Description: Optimizely SDK key
    Value: !Ref ParameterOptimizelySdkKey
