---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys resources needed to support Pinpoint's message personalization capabilities
    Author: James Jory <jjory@amazon.com>

Parameters:
  ResourceBucket:
    Type: String

  ResourceBucketRelativePath:
    Type: String

  ProductsServiceDNSName:
    Type: String

  Uid:
    Type: String
    
Resources:

  # Allows Pinpoint to access Personalize solution and campaign
  PinpointPersonalizeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Uid}-PinptP9e # Referenced by name in messaging notebook
      Path: /
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: pinpoint.amazonaws.com
      Policies:
        - PolicyName: PersonalizeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - personalize:DescribeSolution
                  - personalize:DescribeCampaign
                  - personalize:GetRecommendations
                Resource:
                  - !Sub 'arn:aws:personalize:${AWS::Region}:${AWS::AccountId}:solution/retaildemostore-product-personalization'
                  - !Sub 'arn:aws:personalize:${AWS::Region}:${AWS::AccountId}:campaign/retaildemostore-product-personalization'
                  - !Sub 'arn:aws:personalize:${AWS::Region}:${AWS::AccountId}:filter/retaildemostore-product-personalization'

  CustomizeRecommendationsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: CloudWatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:                    
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                Resource: "arn:aws:logs:*:*:*"

  CustomizeRecommendationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: 'Retail Demo Store function called by Pinpoint to enrich messages with product information based on recommendations from Amazon Personalize'
      Handler: pinpoint-recommender.lambda_handler
      Role: !GetAtt CustomizeRecommendationsFunctionRole.Arn
      Runtime: python3.8
      Code:
        S3Bucket: !Ref ResourceBucket
        S3Key: !Sub '${ResourceBucketRelativePath}aws-lambda/pinpoint-recommender.zip'
      FunctionName: RetailDemoStorePinpointRecommender  # Function name used in notebook to lookup ARN
      Environment:
        Variables:
          products_service_host: !Ref ProductsServiceDNSName

  PinpointPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CustomizeRecommendationsFunction.Arn
      Principal: pinpoint.amazonaws.com
      SourceArn: !Sub 'arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:*'

Outputs:
  PinpointPersonalizeRoleArn:
    Value: !GetAtt PinpointPersonalizeRole.Arn
    
  CustomizeRecommendationsFunctionArn:
    Value: !GetAtt CustomizeRecommendationsFunction.Arn
